version: "3.9"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: aquarium-api
    networks:
      - aquarium
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: aquarium-database
    networks:
      - aquarium
    ports:
      - 1433:1433

  graph:
    build:
      context: graphql
      dockerfile: Dockerfile
    container_name: aquarium-graph
    networks:
      - aquarium
    ports:
      - 4000:4000
    depends_on:
      - api
      - database

networks:
  aquarium:
    driver: bridge