name: Aquarium REST API Release

on:
  push:
    tags:
      - "api-**"
jobs:
  release:
    name: Aquarium REST API Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      
      # Installs Node.js on the github runner.
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      # Run's the test suite to help ensure proper functionality
      - name: Publish to Staging Folder
        working-directory: api
        run: |
          dotnet publish api.csproj -o staging/app --configuration Release /p:Version=${{ github.ref_name }}
          cp -r deploy staging
      
      - name: Create Artifact
        working-directory: api
        run: |
          cd staging
          zip -r ../aquarium-api-${{ github.ref_name }}.zip .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with: 
          target_commitish: ${{ github.sha }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: api/aquarium-api-${{ github.ref_name }}.zip
          generate_release_notes: true