name: Aquarium Database Integration Build

on:
  push:
    branches:
      - main
    paths:
      - 'database/**'
      - 'github/workflows/**'

jobs:
  build:
    name: Aquarium Database Integration Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          ssh-key: ${{ secrets.COMMIT_SSH_KEY }}
      
      # Installs Node.js on the github runner.
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # Run's the test suite to help ensure proper functionality
      - name: Run Build
        working-directory: database
        run: |
          dotnet build

  release:
    name: Create and Publish Aquarium GraphQL API Release
    runs-on: ubuntu-latest
    steps:
      # Checks out the repo
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          ssh-key: ${{ secrets.COMMIT_SSH_KEY }}

      # Installs the git version tool 
      - name: Install GitVersion Tool
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.8.1'

      - name: Calculate Semantic Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true
          configFilePath: ./database/Gitversion.yml
      # - name: Login to Docker
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Login to GHCR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./database
      #     push: true
      #     tags: wmalcolm94/aquarium-database:${{ steps.gitversion.outputs.semVer }}, wmalcolm94/aquarium-database:${{ steps.gitversion.outputs.sha }}

      # Creates a release with the changes in github
      - name: Aquarium Database Release
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.gitversion.outputs.semVer }}',
              name: 'Database ${{ steps.gitversion.outputs.semVer }}',
              generate_release_notes: true
            });